version: '3.1'

services:
  web:
    image: php:7.4-apache
    container_name: lamp_web
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
